SUMMARIZE = "summarize"
RETRIEVE_VALUES = "retrieve_values"
GRADE_DOCUMENTS = "grade_documents"
WRITE_ANSWER = "write_answer"
RETRIEVE_STYLE = "retrieve_style"
WRITE_STYLE = "write_style"
ABORT=  "abort"